OPENAI_COMPAT_BASE_URL = ""
OPENAI_COMPAT_CHAT_COMPLETIONS_URL = ""
OPENAI_COMPAT_DEFAULT_MODEL = "gpt-5.4"
OPENAI_COMPAT_API_KEY = ""

OPENROUTER_BASE_URL = OPENAI_COMPAT_BASE_URL
OPENROUTER_DEFAULT_MODEL = OPENAI_COMPAT_DEFAULT_MODEL
OPENROUTER_API_KEY = OPENAI_COMPAT_API_KEY
